version: "3"
services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: {{ database_name }}
      POSTGRES_USER: {{ database_user }}
      POSTGRES_PASSWORD: {{ database_password }}
    logging:
      options:
        max-size: 100m
        max-file: "3"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: runserver 0.0.0.0:8000
    env_file: .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: {{ database_name }}
      DATABASE_USER: {{ database_user }}
      DATABASE_PASSWORD: {{ database_password }}

    logging:
      options:
        max-size: 100m
        max-file: "3"
    ports:
      # this needs to be set in the shell, compose env vars aren't read yet
      - "${DJANGO_PORT:-8000}:8000"
    volumes:
      - ../../src:{{ service_home }}/main

volumes:
  postgres_data:
